version: "3.9"
services:
  webapi:
    build: .
    command: uvicorn webapi.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./db:/app/db
  worker:
    build: .
    command: python -m worker.main
    env_file: .env
    volumes:
      - ./storage:/app/storage
      - ./db:/app/db
  bot:
    build: .
    command: python -m bot.main
    env_file: .env
    volumes:
      - ./storage:/app/storage
      - ./db:/app/db